# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: gilesknap@gmail.com
author_name: 2ndBrain Obsidian Vault manager
description: Agentic Slack capture system for Obsidian vault
distribution_name: second-brain
docker: false
docs_type: sphinx
git_platform: github.com
github_org: gilesknap
package_name: brain
pypi: false
repo_name: second-brain
strict_typing: true
type_checker: pyright
